parameters:
    phlexible.task.state_file: "@@PhlexibleTaskBundle/Resources/state/state.yml"

services:
    phlexible_task.state_machine:
        class: Finite\StateMachine\StateMachine
        factory: [Phlexible\Bundle\TaskBundle\Finite\StateMachineFactory, factory]
        arguments:
            - "@file_locator"
            - "@event_dispatcher"
            - "%phlexible.task.state_file%"
